// const parametersBodyPart = {
//   men: {
//     none: ["head_length"],
//     hat: ["head_length"],
//     tshirt: ["chest_length", "waist_length"],
//     sweater: ["chest_length", "waist_length"],
//     shirt: ["chest_length", "waist_length"],
//     sweatshirt: ["chest_length", "waist_length"],
//     singlet: ["chest_length", "waist_length"],
//     jacket: ["chest_length", "waist_length"],
//     jeans: ["waist_length", "hip_length"],
//     skirts: ["waist_length", "hip_length"],
//     shorts: ["waist_length", "hip_length"],
//     pants: ["waist_length", "hip_length"],
//     shoes: ["foot_length"],
//     trainers: ["foot_length"],
//   },
//   women: {
//     none: ["head_length", "chest_length", "waist_length", "hip_length", "pants_length", "foot_length"],
//     hat: ["head_length"],
//     tshirt: ["chest_length", "waist_length"],
//     sweater: ["chest_length", "waist_length"],
//     shirt: ["chest_length", "waist_length"],
//     sweatshirt: ["chest_length", "waist_length"],
//     singlet: ["chest_length", "waist_length"],
//     jacket: ["chest_length", "waist_length"],
//     jeans: ["waist_length", "hip_length"],
//     skirts: ["waist_length", "hip_length"],
//     shorts: ["waist_length", "hip_length"],
//     pants: ["waist_length", "hip_length"],
//     shoes: ["foot_length"],
//     trainers: ["foot_length"],
//   },
//   child: {
//     none: ["head_length", "chest_length", "waist_length", "height", "hip_length", "pants_length", "foot_length"],
//     hat: ["head_length"],
//     tshirt: ["chest_length", "waist_length"],
//     sweater: ["chest_length", "waist_length"],
//     shirt: ["chest_length", "waist_length"],
//     sweatshirt: ["chest_length", "waist_length"],
//     singlet: ["chest_length", "waist_length"],
//     jacket: ["chest_length", "waist_length"],
//     jeans: ["waist_length", "hip_length"],
//     skirts: ["waist_length", "hip_length"],
//     shorts: ["waist_length", "hip_length"],
//     pants: ["waist_length", "hip_length"],
//     shoes: ["foot_length"],
//     trainers: ["foot_length"],
//   }
// };

// export { parametersBodyPart };
